"""
base.py

Defines the core data structures and shared base interfaces for the
provider integrations. Ensures that all API wrappers return standardized
metrics and outputs for downstream evaluation and UI rendering.
"""
from dataclasses import dataclass


@dataclass(frozen=True)
class ProviderExperimentResult:
    """
    A standardized data object representing the output and approximate
    metrics from a single provider API execution.

    Attributes:
        output_text (str): The raw text response generated by the model.
        latency_seconds (float): The elapsed time taken for the API call.
        approximate_input_tokens (int): The estimated number of prompt tokens.
        approximate_output_tokens (int): The estimated number of completion tokens.
        approximate_total_tokens (int): The combined input and output token count.
        approximate_context_pressure_percent (float | None): The % of the context window used.
        approximate_cost_usd (float | None): The estimated cost of the call in USD.
    """
    output_text: str
    latency_seconds: float
    approximate_input_tokens: int
    approximate_output_tokens: int
    approximate_total_tokens: int
    approximate_context_pressure_percent: float | None
    approximate_cost_usd: float | None
